#!/bin/bash
#
# Purpose: Completely purge a named user from the web catalog with all his content.
#
# Author: Christian Berg
# Initial creation: 28/01/2014
# Absolutely no warranty, use at your own risk
# Please include this header in any copy or reuse of the script you make
#
# Current version: 1.0
#
# Change log:
#        CBERG 28/01/2014 Intial creation
#


########################################################################################
# Step 1: Kill the users personal folder plus content with its accompagning .atr       #
########################################################################################

cd $1/root/users

find -type d -name $2 | xargs rm -rf
find -name $2.atr | xargs rm -f

########################################################################################
# Step 2: Kill the users entries in /system/users                                      #
# Two files will be affected "username" and "username.atr"                             #
# Removal happens one-by-one                                                           #
########################################################################################

cd $1/root/system/security/users

find -name $2 | xargs rm -f
find -name $2.atr | xargs rm -f

########################################################################################
# Step 3: Kill the users entries in /system/accountids                                 #
# Two files will be affected. Accountids contains the translation from GUID to         #
# username, so the actual username resides within the files content rather than its    #
# name. Bulk removal.                                                                  #
########################################################################################

cd $1/root/system/security/accountids

grep -r -l $2 . | xargs rm -f

echo User $2 has been purged from the web catalog.

exit 0 
